### ISSUE TITLE
setup_s3_file_notification.sh script run does not do anything

### ISSUE THREAD

**Issue by kamipatel** [forcedotcom/file-notifier-for-blob-store#25]
When I run 
./setup_s3_file_notification.sh input_parameters_s3.conf
I get following message but it does not do anything after that e.g. create lambda function

aws CLI is already installed, skipping the installation
Please export all the three AWS credentials (AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN) and paste it to terminal (please use https://docs.aws.amazon.com/keyspaces/latest/devguide/access.credentials.html to generate it)_

**Comment by kamipatel** [comment]
I fixed the issue. I had to remove AWS_SESSION_TOKEN from script. 

Please consider it closed.

Thanks!

**Comment by KhyathiSriNavya227** [comment]
Hi @kamipatel,
I have removed the AWS_SESSION_TOKEN variable from the script file and tried again configuring AWS credentials, still facing same issue. Can you please tell me how to resolve this issue?
Error.
All the s3 cloud function installer logs are logged to log_2025-03-05_22:26:09.txt file
aws CLI is already installed, skipping the installation
Please export all the three AWS credentials (AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY and AWS_SESSION_TOKEN) and paste it to terminal (please use https://docs.aws.amazon.com/keyspaces/latest/devguide/access.credentials.html to generate it)
TIA
